import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../',import.meta.url)).replace(/\/$/,'');const require=createRequire(root+'/package.json');const wr=createRequire(require.resolve('wrangler/package.json'));const {Miniflare}=wr('miniflare');
const names=readdirSync(root+'/dist/server',{recursive:true}).filter(x=>x.endsWith('.js'));const modules=['index.js',...names.filter(x=>x!=='index.js')].map(x=>({type:'ESModule',path:root+'/dist/server/'+x}));
const secret='local-runtime-test-only';const mf=new Miniflare({modules,modulesRoot:root+'/dist/server',modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{STRIPE_WEBHOOK_SECRET:secret,OWNER_EMAIL:'operator@example.com'},assets:{directory:root+'/dist/client',binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}}});
let checks=0;function pass(msg){checks++;console.log('PASS '+msg);}
const headers={'oai-authenticated-user-id':'test-owner','oai-authenticated-user-email':'test@example.com','origin':'https://example.com','content-type':'application/json'};const other={...headers,'oai-authenticated-user-id':'other-owner'};
const fetch=(path,options={})=>mf.dispatchFetch('https://example.com'+path,options);
async function webhook(event){const timestamp=Math.floor(Date.now()/1000),body=JSON.stringify(event);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(timestamp+'.'+body));const hex=Buffer.from(sig).toString('hex');return fetch('/api/webhook',{method:'POST',headers:{'stripe-signature':`t=${timestamp},v1=${hex}`},body});}
try{const db=await mf.getD1Database('DB');for(const filename of readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort()){for(const statement of readFileSync(root+'/drizzle/'+filename,'utf8').split('--> statement-breakpoint'))await db.exec(statement.trim().replaceAll('\n',' '));}
let r=await fetch('/');assert.equal(r.status,200);assert.match(await r.text(),/back to business/);pass('homepage renders');
r=await fetch('/pdf.worker.min.mjs');assert.equal(r.status,200);assert.ok((await r.text()).length>100000);pass('local PDF worker packaged');
r=await fetch('/api/cases');assert.equal(r.status,401);pass('anonymous cases blocked');
r=await fetch('/api/status');assert.equal((await r.json()).paymentsEnabled,false);pass('payments closed without full launch configuration');
const data={business:'Runtime Test',email:'test@example.com',profileId:'test-profile',mapsUrl:'',address:'',previousAddress:'',type:'service',issue:'suspended',notice:'Test notice',corrections:'',caseNumber:'',status:'Preparing',checks:[],events:[],draft:'',triage:{accountRestricted:'yes'},records:[{id:'test-record',label:'Original',profileId:'test-profile',mapsUrl:'',address:'',reviews:'12',observed:'2026-09-26',access:'unknown',preferred:true}],followupDrafts:{access:'User-edited draft'},paid:true,paidUntil:'2099-01-01'};
r=await fetch('/api/cases',{method:'POST',headers,body:JSON.stringify(data)});const saved=await r.json();assert.ok(saved.id);assert.equal(saved.paid,false);pass('case saves without accepting injected entitlement');
r=await fetch('/api/cases',{headers});const rows=await r.json();assert.equal(rows.cases[0].records[0].profileId,'test-profile');assert.equal(rows.cases[0].followupDrafts.access,'User-edited draft');pass('profile comparison and edited draft persist');
r=await fetch('/api/cases',{method:'POST',headers,body:JSON.stringify({...data,id:saved.id,version:saved.version,notice:'Updated notice'})});assert.equal(r.status,200);r=await fetch('/api/history?caseId='+saved.id,{headers});const history=await r.json();assert.equal(history.versions.length,1);r=await fetch('/api/history?caseId='+saved.id+'&id='+history.versions[0].id,{headers});assert.equal((await r.json()).data.notice,'Test notice');r=await fetch('/api/history?caseId='+saved.id,{headers:other});assert.equal(r.status,404);pass('earlier text saved and history isolated by owner');
r=await fetch('/packet?example=1');assert.equal(r.status,200);assert.match(await r.text(),/Fictional sample packet/);r=await fetch('/packet?id='+saved.id,{headers});assert.match(await r.text(),/A Case Pass is required/);pass('printable example renders and free private packet is gated');

r=await fetch('/api/cases',{headers:other});assert.equal((await r.json()).cases.length,0);pass('cross-owner case isolation');
r=await fetch('/api/account/export',{headers});const backup=await r.json();assert.equal(backup.cases.length,1);assert.equal(backup.format,'profilepath-backup');r=await fetch('/api/account/export',{headers:other});assert.equal((await r.json()).cases.length,0);pass('free backups are owner-scoped');
r=await fetch('/api/export?id='+saved.id,{headers});assert.equal(r.status,402);pass('unpaid prepared packet blocked');
r=await fetch('/api/launch',{headers});assert.equal(r.status,403);r=await fetch('/api/launch',{headers:{...headers,'oai-authenticated-user-email':'operator@example.com'}});assert.equal(r.status,200);assert.ok((await r.json()).checks.some(c=>!c.ready));pass('operator launch status rejects customer access');
r=await fetch('/api/cases',{method:'POST',headers,body:JSON.stringify({...data,id:saved.id,version:999})});assert.equal(r.status,409);pass('stale writes rejected');
r=await fetch('/api/cases',{method:'POST',headers:{...headers,origin:'https://evil.example'},body:JSON.stringify(data)});assert.notEqual(r.status,200);pass('cross-origin writes rejected');
const now=Math.floor(Date.now()/1000);const session={id:'cs_local_test',created:now,mode:'payment',payment_status:'paid',amount_total:7900,currency:'usd',payment_intent:'pi_local_test',metadata:{case_id:saved.id,user_id:'test-owner',terms_version:'2026-09-26-preview'}};
r=await webhook({type:'checkout.session.completed',created:now,data:{object:{...session,payment_status:'unpaid'}}});assert.equal(r.status,200);assert.equal((await db.prepare('SELECT paid FROM cases WHERE id=?').bind(saved.id).first()).paid,0);pass('unpaid checkout event does not grant access');
r=await webhook({type:'checkout.session.async_payment_succeeded',created:now,data:{object:session}});assert.equal(r.status,200);const granted=await db.prepare('SELECT paid,paid_until FROM cases WHERE id=?').bind(saved.id).first();assert.equal(granted.paid,1);assert.ok(Date.parse(granted.paid_until)>Date.now());pass('verified delayed payment grants expiring pass');
r=await webhook({type:'checkout.session.completed',created:now+300,data:{object:session}});assert.equal(r.status,200);assert.equal((await db.prepare('SELECT paid_until FROM cases WHERE id=?').bind(saved.id).first()).paid_until,granted.paid_until);pass('duplicate event cannot extend access');
r=await fetch('/api/export?id='+saved.id,{headers});assert.equal(r.status,200);assert.match(await r.text(),/User-edited draft/);pass('paid packet includes follow-up draft');r=await fetch('/packet?id='+saved.id,{headers});assert.match(await r.text(),/User-edited draft/);r=await fetch('/packet?id='+saved.id,{headers:other});assert.match(await r.text(),/Case not available/);pass('printable paid packet includes case text and rejects another owner');
const file=new FormData();file.set('caseId',saved.id);file.set('file',new File(['%PDF-1.4\ntest bytes'], 'test.pdf',{type:'application/pdf'}));const uploadRequest=new Request('https://example.com/api/evidence',{method:'POST',body:file});r=await fetch('/api/evidence',{method:'POST',headers:{'oai-authenticated-user-id':'test-owner','oai-authenticated-user-email':'test@example.com',origin:'https://example.com','content-type':uploadRequest.headers.get('content-type')},body:await uploadRequest.arrayBuffer()});const uploaded=await r.json();assert.ok(uploaded.id);r=await fetch('/api/evidence?id='+uploaded.id,{headers:other});assert.equal(r.status,404);pass('evidence upload and cross-owner isolation');
r=await webhook({type:'charge.refunded',created:now+1,data:{object:{payment_intent:'pi_local_test',refunded:true,metadata:session.metadata}}});assert.equal(r.status,200);r=await webhook({type:'checkout.session.completed',created:now+2,data:{object:session}});assert.equal(r.status,200);r=await fetch('/api/export?id='+saved.id,{headers});assert.equal(r.status,402);r=await fetch('/api/evidence?id='+uploaded.id,{headers});assert.equal(r.status,200);pass('refund revokes paid tools despite replay and retains document download');
r=await fetch('/api/cases?id='+saved.id,{method:'DELETE',headers});assert.equal(r.status,200);assert.equal(await (await mf.getR2Bucket('BUCKET')).get(uploaded.id),null);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM case_versions WHERE case_id=?').bind(saved.id).first()).n,0);pass('case deletion removes evidence bytes and text snapshots');
console.log(`${checks} runtime checks passed.`);
}finally{await mf.dispose();}
