import {z} from 'zod';
import {db,identity,operator,sameOrigin,owned,failure,rateLimit} from '@/lib/server';
const noStore={'Cache-Control':'private, no-store'};
async function ticket(id:string,userId:string,admin:boolean){return db().prepare('SELECT * FROM support_tickets WHERE id=?'+(admin?'':' AND user_id=?')).bind(...(admin?[id]:[id,userId])).first<{id:string;user_id:string;case_id:string|null;share_case:number;status:string}>();}
export async function GET(req:Request){try{const u=await identity();const p=new URL(req.url).searchParams;const admin=p.get('operator')==='1';if(admin)await operator();const id=p.get('id');if(id){const t=await ticket(id,u.userId,admin);if(!t)return Response.json({error:'Support request not found.'},{status:404});const messages=await db().prepare('SELECT id,author,body,created FROM support_messages WHERE ticket_id=? ORDER BY created,id').bind(id).all();const shared=admin&&t.share_case&&t.case_id?await owned(t.case_id,t.user_id):null;return Response.json({ticket:t,messages:messages.results,sharedCase:shared?JSON.parse(shared.data):null},{headers:noStore});}const state=p.get('status');const where=admin?(state&&['open','waiting','resolved'].includes(state)?' WHERE status=?':''):' WHERE user_id=?';const args=admin?(where?[state]:[]):[u.userId];const rows=await db().prepare('SELECT id,subject,category,status,case_id,share_case,created,updated'+(admin?',email,user_id':'')+' FROM support_tickets'+where+' ORDER BY updated DESC LIMIT 100').bind(...args).all();return Response.json({tickets:rows.results},{headers:noStore});}catch(e){return failure(e);}}
const create=z.object({subject:z.string().trim().min(4).max(150),category:z.enum(['using-the-site','case-guidance','billing','privacy','bug']),body:z.string().trim().min(10).max(5000),caseId:z.string().max(100).optional(),shareCase:z.boolean().default(false)});
const reply=z.object({id:z.string().max(100),body:z.string().trim().max(5000).default(''),status:z.enum(['open','waiting','resolved']).optional(),shareCase:z.boolean().optional(),operator:z.boolean().default(false)});
export async function POST(req:Request){try{sameOrigin(req);const u=await identity();await rateLimit(u.userId,'support',8);if(Number(req.headers.get('content-length'))>20000)throw Error('Support request is too large.');const raw=await req.text();if(raw.length>20000)throw Error('Support request is too large.');const input=JSON.parse(raw);const now=new Date().toISOString();if(input.id){const v=reply.parse(input);if(v.operator)await operator();const t=await ticket(v.id,u.userId,v.operator);if(!t)return Response.json({error:'Support request not found.'},{status:404});if(!v.body&&!v.status&&v.shareCase===undefined)throw Error('Enter a reply or update the request.');const n=await db().prepare('SELECT COUNT(*) AS n FROM support_messages WHERE ticket_id=?').bind(v.id).first<{n:number}>();if(v.body&&(n?.n||0)>=200)throw Error('Support thread is full. Open a new request.');const statements=[db().prepare('UPDATE support_tickets SET status=?,share_case=COALESCE(?,share_case),updated=? WHERE id=?').bind(v.status||(v.body?(v.operator?'waiting':'open'):t.status),!v.operator&&v.shareCase!==undefined?(v.shareCase?1:0):null,now,v.id)];if(v.body)statements.push(db().prepare('INSERT INTO support_messages (id,ticket_id,author,body,created) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM support_tickets WHERE id=?)').bind(crypto.randomUUID(),v.id,v.operator?'support':'customer',v.body,now,v.id));const mutations=await db().batch(statements);if(!mutations[0].meta.changes)return Response.json({error:'Support request not found.'},{status:404});return Response.json({id:v.id});}const v=create.parse(input);if(v.caseId&&!await owned(v.caseId,u.userId))throw Error('Case not found.');const id=crypto.randomUUID();const count=await db().prepare('SELECT COUNT(*) AS n FROM support_tickets WHERE user_id=?').bind(u.userId).first<{n:number}>();if((count?.n||0)>=100)throw Error('Support request limit reached. Continue an existing thread.');await db().batch([db().prepare('INSERT INTO support_tickets (id,user_id,email,subject,category,status,case_id,share_case,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,u.userId,u.email,v.subject,v.category,'open',v.caseId||null,v.caseId&&v.shareCase?1:0,now,now),db().prepare('INSERT INTO support_messages (id,ticket_id,author,body,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,'customer',v.body,now)]);return Response.json({id},{status:201});}catch(e){return failure(e);}}
export async function DELETE(req:Request){try{sameOrigin(req);const u=await identity();const id=new URL(req.url).searchParams.get('id')||'';const t=await ticket(id,u.userId,false);if(!t)return new Response(null,{status:404});await db().batch([db().prepare('DELETE FROM support_messages WHERE ticket_id=?').bind(id),db().prepare('DELETE FROM support_tickets WHERE id=? AND user_id=?').bind(id,u.userId)]);return Response.json({deleted:true});}catch(e){return failure(e);}}
