'use client';
import {useEffect,useState,useRef} from 'react';
import {Download,ExternalLink,Upload,CheckCircle2,TriangleAlert} from 'lucide-react';
import {toast} from 'sonner';
import {schema} from '@/lib/case-schema';
import {type CaseData} from '@/lib/recovery';
export type AccountStatus={signedIn:boolean;email:string|null;paymentsEnabled:boolean;isOperator?:boolean;supportEmail?:string|null;operatorName?:string|null;refundPolicy?:string|null};
export default function AccountTools({account,onImport}:{account:AccountStatus;onImport:(c:CaseData)=>void}){const [purchases,setPurchases]=useState<{id:string;case_id:string;status:string;created:string;expires:string}[]>([]);const [launch,setLaunch]=useState<{checks:{label:string;ready:boolean}[];manualChecks:string[]}|null>(null);const input=useRef<HTMLInputElement>(null);const [backupCases,setBackupCases]=useState<CaseData[]>([]);const [backupIndex,setBackupIndex]=useState('0');
 useEffect(()=>{if(!account.signedIn)return;void fetch('/api/purchases').then(async r=>{if(!r.ok)throw Error();setPurchases(((await r.json()) as {purchases:typeof purchases}).purchases);}).catch(()=>toast.error('Purchase history could not be loaded.'));if(account.isOperator)void fetch('/api/launch').then(async r=>{if(!r.ok)throw Error();setLaunch(await r.json());}).catch(()=>toast.error('Launch status could not be loaded.'));},[account.signedIn,account.isOperator]);
 async function restore(file?:File){try{if(!file)return;if(file.size>10000000)throw Error('Choose a backup under 10 MB.');const backup=JSON.parse(await file.text());if(backup.format!=='profilepath-backup'||backup.version!==1||!Array.isArray(backup.cases)||!backup.cases.length)throw Error('Choose a ProfilePath data backup containing a case.');if(backup.cases.length>20)throw Error('The backup contains too many cases.');const checked=backup.cases.map((x:unknown)=>{const first=schema.parse(x);return {...first,id:undefined,version:undefined,paid:false,paidUntil:undefined} as CaseData;});setBackupCases(checked);setBackupIndex('0');toast.info('Choose which case to restore. Original files and paid access are not restored.');}catch(e){toast.error(e instanceof SyntaxError?'The backup is not valid JSON.':(e as Error).message);}finally{if(input.current)input.current.value='';}}
 return <div className="account-tools"><section className="panel"><span className="eyebrow muted">YOUR DATA, YOUR COPY</span><h2>Back up your work</h2><p>Download all saved case text, checklists, follow-up drafts, profile comparisons and document names. Download original files individually from the evidence locker. Data export is free.</p><div className="draft-actions"><a className="button" href="/api/account/export"><Download size={16}/>Download my data</a><button className="button" onClick={()=>input.current?.click()}><Upload size={16}/>Restore a case backup</button><input hidden ref={input} type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/></div>{backupCases.length>0&&<div className="backup-picker"><label className="field"><span>Case to restore</span><select value={backupIndex} onChange={e=>setBackupIndex(e.target.value)}>{backupCases.map((c,i)=><option key={i} value={i}>{c.business}</option>)}</select></label><button className="button primary" onClick={()=>onImport(backupCases[Number(backupIndex)])}>Open selected case for review</button></div>}<p className="fine">Choose a case from your backup, review it, then save it as a new case. Existing cases are never overwritten.</p></section><section className="panel"><span className="eyebrow muted">PURCHASE HISTORY</span><h2>Case Passes & receipts</h2>{purchases.length?purchases.filter(p=>!p.id.startsWith('hold-')).map(p=><div className="purchase-row" key={p.id}><div><strong>Recovery Case Pass · {p.status}</strong><p>Purchased {new Date(p.created).toLocaleDateString()}{p.expires?' · Access through '+new Date(p.expires).toLocaleDateString():''}</p></div><button className="button" onClick={async()=>{try{const r=await fetch('/api/purchases/receipt?id='+encodeURIComponent(p.id));const j=await r.json() as {error?:string;url:string};if(!r.ok)throw Error(j.error);window.location.assign(j.url);}catch(e){toast.error((e as Error).message);}}}>Receipt <ExternalLink size={14}/></button></div>):<p>No purchases yet. Free diagnosis and saved cases are available without a Case Pass.</p>}{account.supportEmail&&<a className="text-button" href={'mailto:'+account.supportEmail}>Contact customer support</a>}</section>{account.isOperator&&<section className="panel launch-panel"><span className="eyebrow muted">VISIBLE ONLY TO THE OPERATOR</span><h2>Launch readiness</h2><p>These checks show configuration, not proof that a purchase has been tested. Payment collection stays closed until every required setting is ready.</p>{launch?<><div className="launch-checks">{launch.checks.map(c=><div key={c.label}>{c.ready?<CheckCircle2 size={19}/>:<TriangleAlert size={19}/>}<span>{c.label}</span><b>{c.ready?'Configured':'Needed'}</b></div>)}</div><h3>Complete before opening sales</h3><ul>{launch.manualChecks.map(x=><li key={x}>{x}</li>)}</ul></>:<p>Loading launch checks…</p>}</section>}</div>;
}
