'use client';
import {useEffect,useState} from 'react';
import {History,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type CaseData,issues} from '@/lib/recovery';
import {schema} from '@/lib/case-schema';
import {toast} from 'sonner';
type Version={id:string;version:number;created:string};
export default function CaseHistory({c,restore}:{c:CaseData;restore:(data:CaseData)=>void}){const [open,setOpen]=useState(false);const [versions,setVersions]=useState<Version[]>([]);const [selected,setSelected]=useState<CaseData|null>(null);const [loading,setLoading]=useState(false);useEffect(()=>{if(!open||!c.id)return;let active=true;setLoading(true);setSelected(null);fetch('/api/history?caseId='+encodeURIComponent(c.id)).then(async r=>{const j=await r.json() as {versions:Version[];error?:string};if(!r.ok)throw Error(j.error);if(active)setVersions(j.versions);}).catch(e=>toast.error(e.message)).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[open,c.id,c.version]);async function inspect(v:Version){setLoading(true);setSelected(null);try{const r=await fetch('/api/history?caseId='+encodeURIComponent(c.id!)+'&id='+encodeURIComponent(v.id));const j=await r.json() as {data:unknown;error?:string};if(!r.ok)throw Error(j.error);setSelected(schema.parse(j.data) as CaseData);}catch(e){toast.error((e as Error).message);}finally{setLoading(false);}}
 return <><button className="text-button" onClick={()=>setOpen(true)}><History size={15}/>Saved version history</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="history-modal"><DialogHeader><DialogTitle>Recover an earlier version</DialogTitle><DialogDescription>We keep the previous 10 saved text versions of this case. This does not restore deleted documents or change paid access.</DialogDescription></DialogHeader>{loading?<p>Loading saved versions…</p>:!versions.length?<p>Earlier versions appear after you edit and save this case again.</p>:<div className="history-versions">{versions.map(v=><button className="button" key={v.id} onClick={()=>void inspect(v)}>Version {v.version} · {new Date(v.created).toLocaleString()}</button>)}</div>}{selected&&<div className="history-preview"><h3>{selected.business}</h3><p>{issues[selected.issue].short} · {selected.status}</p><p>{selected.checks.length} checkmarks · {selected.events.length} timeline entries</p><pre>{selected.draft||selected.notice||'No draft or notice in this version.'}</pre><button className="button primary" onClick={()=>{restore({...selected,id:c.id,version:c.version,paid:c.paid,paidUntil:c.paidUntil});setOpen(false);toast.info('Earlier text loaded for review. Save changes to keep it. Existing document files are unchanged.');}}><RotateCcw size={16}/>Load this text for review</button></div>}</DialogContent></Dialog></>;}
