'use client';
import {useState} from 'react';
import {ArrowRight,ClipboardCheck,ExternalLink,SlidersHorizontal} from 'lucide-react';
import type {CaseData} from '@/lib/recovery';
import {issues,sources} from '@/lib/recovery';
import {reviewCase,type Triage} from '@/lib/case-review';
export default function CaseReview({c,update}:{c:CaseData;update:(p:Partial<CaseData>)=>void}){
 const [open,setOpen]=useState(false);const r=reviewCase(c);const t=c.triage||{};
 const change=(p:Partial<Triage>)=>update({triage:{...t,...p}});
 const questions=[['accountRestricted','Does Google say your managing account is restricted?'],['managementAccess','Can you manage the original profile?'],['publicVisible','Is the original profile visible on Maps?'],...(c.type==='service'?[['addressVisible','Is your operating address shown publicly?']]:[]),...(['storefront','hybrid'].includes(c.type)?[['permanentSignage','Does the location have permanent fixed business signage?']]:[])] as [keyof Triage,string][];
 return <section className="review-panel" aria-label="Case review"><div className="review-header"><span className="review-icon"><ClipboardCheck size={24}/></span><div><span className="eyebrow">YOUR CASE, CONNECTED</span><h2>Know what matters next.</h2></div><span className="pill">Live checklist</span></div><p className="review-next">{r.next}</p>{r.route!==c.issue&&<div className="route-recommendation"><strong>Recommended route: {issues[r.route].short}</strong><p>{r.reason}</p><button className="button primary" onClick={()=>update({issue:r.route,checks:c.checks.filter(x=>!x.startsWith('step-'))})}>Use this recovery route <ArrowRight size={16}/></button><small>Your old route’s task checkmarks will reset. Your evidence and draft stay in the case.</small></div>}<button className="review-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><SlidersHorizontal size={17}/>{open?'Close case questions':'Refine my plan with case questions'}<span>{open?'−':'+'}</span></button>{open&&<div className="review-questions"><p>Answer from what you can actually see. “Not checked” is useful too. These answers are saved with your case.</p>{questions.map(([key,label])=><label className="field" key={key}><span>{label}</span><select value={t[key]||'unknown'} onChange={e=>change({[key]:e.target.value})}><option value="unknown">Not checked / unsure</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}<div className="form-grid"><label className="field"><span>Business name on supporting document</span><input maxLength={150} value={t.documentName||''} onChange={e=>change({documentName:e.target.value})} placeholder="Copy exactly from the document"/></label><label className="field"><span>Address on supporting document</span><input maxLength={500} value={t.documentAddress||''} onChange={e=>change({documentAddress:e.target.value})} placeholder="Copy exactly from the document"/></label></div><p className="fine">Text comparisons flag differences for your review. They do not authenticate documents or determine eligibility.</p></div>}<div className="review-findings">{r.findings.map(f=><article key={f.title} className={'review-finding '+f.level}><span className="finding-dot"/><div><strong>{f.title}</strong><p>{f.detail}</p><a href={sources[f.source].url} target="_blank" rel="noopener noreferrer">Check Google’s guidance <ExternalLink size={12}/></a></div></article>)}</div><p className="fine">Based on your answers. No connection to Google’s internal systems and no prediction of reinstatement.</p></section>;
}
