'use client';
import {useEffect,useRef,useState} from 'react';
import {FileSearch,Upload,CheckCircle2} from 'lucide-react';
import {toast} from 'sonner';
import {readDocument,documentChecks,type DocumentRead} from '@/lib/document-reader';
export default function DocumentReader({business='',address='',onNotice}:{business?:string;address?:string;onNotice?:(text:string)=>void}){
 const [result,setResult]=useState<DocumentRead|null>(null);const [text,setText]=useState('');const[progress,setProgress]=useState('');const[error,setError]=useState('');const job=useRef<AbortController|null>(null);
 useEffect(()=>()=>job.current?.abort(),[]);
 async function read(file?:File){if(!file)return;job.current?.abort();const controller=new AbortController();job.current=controller;setError('');setResult(null);setProgress('Opening document…');try{const r=await readDocument(file,controller.signal,s=>{if(job.current===controller)setProgress(s);});if(controller.signal.aborted||job.current!==controller)return;setResult(r);setText(r.text);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to read this document.');}finally{if(job.current===controller){setProgress('');job.current=null;}}}
 return <section className="document-reader"><div className="section-top"><div><span className="eyebrow muted">PRIVATE DOCUMENT REVIEW</span><h3>Read a scan, photo or PDF</h3></div><label className="button"><Upload size={16}/>{progress?'Reading…':'Choose document'}<input disabled={!!progress} type="file" className="sr-only" accept=".pdf,.png,.jpg,.jpeg,.txt,.md" onChange={e=>{void read(e.target.files?.[0]);e.target.value='';}}/></label></div><p>English text recognition runs in your browser. The original stays on your device. Up to 10 MB, 15 PDF pages or 8 scanned pages per file.</p>{progress&&<div className="reader-progress" role="status"><FileSearch size={18}/><span>{progress}</span><button className="text-button" onClick={()=>{job.current?.abort();job.current=null;setProgress('');}}>Cancel</button></div>}{error&&<p className="notice" role="alert">{error}</p>}{result&&<div className="reader-result"><div className="reader-pages">{result.pages.map(p=><span className="pill" key={p.page}>Page {p.page} · {p.method==='ocr'?`OCR · ${p.confidence}% recognition confidence`:'Selectable text'}</span>)}</div><p className="fine">Recognition confidence measures the reader’s text estimate, not document authenticity or acceptance by Google. Check every name, address, ID and date against the original.</p><label className="field"><span>Review and correct extracted text</span><textarea rows={8} maxLength={60000} value={text} onChange={e=>setText(e.target.value)}/></label><div className="document-checks">{documentChecks(text,business,address).map(x=><div key={x.label}><CheckCircle2 size={17}/><div><strong>{x.label}</strong><p>{x.detail}</p></div></div>)}</div>{onNotice&&<div className="draft-actions"><button className="button primary" disabled={!text.trim()||text.length>5000} onClick={()=>{onNotice(text.trim());toast.success('Reviewed text applied. Save your case to keep it.');}}>Use reviewed text as my notice</button><span className="fine">{text.length.toLocaleString()} / 5,000 characters for a notice. Trim to the relevant decision first.</span></div>}<p className="fine">These checks flag text to review. They cannot verify authenticity, eligibility, signatures or a suspension cause. Recognition errors are possible; no document is marked “approved.”</p><button className="text-button" onClick={()=>{setResult(null);setText('');}}>Clear extracted text</button></div>}</section>;
}
