export type ReadPage={page:number;text:string;method:'text'|'ocr';confidence?:number};
export type DocumentRead={name:string;pages:ReadPage[];text:string};
export async function readDocument(file:File,signal:AbortSignal,progress:(text:string)=>void):Promise<DocumentRead>{
 if(file.size>10*1024*1024)throw Error('Choose a document under 10 MB.');
 let worker:import('tesseract.js').Worker|undefined;let pdfTask:import('pdfjs-dist').PDFDocumentLoadingTask|undefined;let render:import('pdfjs-dist').RenderTask|undefined;
 let finished=false;const pages:ReadPage[]=[];const aborted=()=>{if(signal.aborted)throw new DOMException('Reading canceled','AbortError');};
 let rejectAbort:(e:Error)=>void=()=>{};const abortPromise=new Promise<never>((_,reject)=>{rejectAbort=reject;});void abortPromise.catch(()=>{});
 const cleanup=()=>{render?.cancel();if(worker)void worker.terminate().catch(()=>{});if(pdfTask)void pdfTask.destroy().catch(()=>{});};const cancel=()=>{cleanup();rejectAbort(new DOMException('Reading canceled','AbortError'));};signal.addEventListener('abort',cancel,{once:true});
 const race=<T,>(p:Promise<T>)=>Promise.race([p,abortPromise]);
 async function recognize(canvas:HTMLCanvasElement,page:number){aborted();if(!worker){progress('Preparing private document reader…');const {createWorker,PSM}=await import('tesseract.js');const pendingWorker=createWorker('eng',1,{workerPath:'/ocr/worker.min.js',corePath:'/ocr/core',langPath:'/ocr/lang',workerBlobURL:false,errorHandler:()=>rejectAbort(new Error('The document reader could not load. Check your connection and try again.')),logger:m=>{if(!signal.aborted)progress(m.status==='recognizing text'?`Reading page ${page} · ${Math.round(m.progress*100)}%`:'Preparing document reader…');}});void pendingWorker.then(w=>{if(signal.aborted||finished)void w.terminate().catch(()=>{});}).catch(()=>{});worker=await race(pendingWorker);if(signal.aborted){await worker.terminate();aborted();}await race(worker.setParameters({tessedit_pageseg_mode:PSM.AUTO,user_defined_dpi:'300'}));}const {data}=await race(worker.recognize(canvas));aborted();pages.push({page,text:data.text.trim(),method:'ocr',confidence:Math.round(data.confidence)});canvas.width=1;canvas.height=1;}
 try{aborted();if(/\.(txt|md)$/i.test(file.name)){pages.push({page:1,text:await file.text(),method:'text'});}else if(/\.pdf$/i.test(file.name)){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';pdfTask=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),wasmUrl:'/pdf-wasm/',cMapUrl:'/pdf-cmaps/',cMapPacked:true,standardFontDataUrl:'/pdf-fonts/'});const pdf=await race(pdfTask.promise);if(pdf.numPages>15)throw Error('Choose a document with 15 pages or fewer.');let scanned=0;for(let n=1;n<=pdf.numPages;n++){aborted();progress(`Reading page ${n} of ${pdf.numPages}`);const page=await race(pdf.getPage(n));const content=await race(page.getTextContent());const text=content.items.map(x=>'str'in x?x.str:'').join(' ').trim();if(text.length>=40){pages.push({page:n,text,method:'text'});}else{if(++scanned>8)throw Error('Choose up to eight scanned pages at a time. Split this PDF and try again.');const base=page.getViewport({scale:1});const scale=Math.min(300/72,Math.sqrt(6_000_000/(base.width*base.height)));const viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);render=page.render({canvas,viewport,background:'#ffffff'});await race(render.promise);render=undefined;await recognize(canvas,n);}page.cleanup();if(pages.reduce((n,p)=>n+p.text.length,0)>60000)throw Error('The document contains too much text. Import the relevant pages only.');}}else if(/\.(png|jpe?g)$/i.test(file.name)){const bitmap=await createImageBitmap(file);try{aborted();if(bitmap.width*bitmap.height>40_000_000)throw Error('Choose a smaller photo, under 40 megapixels.');const scale=Math.min(1,Math.sqrt(6_000_000/(bitmap.width*bitmap.height)));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);await recognize(canvas,1);}finally{bitmap.close();}}else throw Error('Choose a PDF, JPG, PNG or text document.');aborted();const text=pages.map(p=>p.text).join('\n\n');if(!text.trim())throw Error('No readable text detected. Try a straight, well-lit image or enter the wording manually.');if(text.length>60000)throw Error('Import only the relevant pages, under 60,000 characters.');return {name:file.name,pages,text};}finally{finished=true;signal.removeEventListener('abort',cancel);cleanup();}
}
export function documentChecks(text:string,business:string,address:string){const norm=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();const found=(s:string)=>!!norm(s)&&norm(text).includes(norm(s));return [{label:'Business name',detail:!business?'Add your business name to compare.':found(business)?'Business-name wording appears in the extracted text.':'Business-name wording was not found. Compare spelling and any trading name with the original.'},{label:'Operating address',detail:!address?'Add the operating address to compare.':found(address)?'Address wording appears in the extracted text.':'Exact address wording was not found. Abbreviations, OCR errors or a different address can cause this.'},{label:'Dates',detail:/\b(?:20\d{2}|\d{1,2}[/-]\d{1,2}[/-]\d{2,4})\b/.test(text)?'Date-like text detected. Check the issue date and expiry on the original.':'No obvious date detected. Check the original for an issue date and expiry.'},{label:'Privacy',detail:/\b\d{3}-\d{2}-\d{4}\b|\b(?:account number|social security|bank account)\b/i.test(text)?'Potential sensitive identifiers found. Remove unnecessary private data from the copy you submit.':'Review the original for unnecessary private information before sharing.'}];}
