import type {Triage} from './case-review.ts';
export type Issue = 'suspended'|'restricted'|'ownership'|'verification'|'reviews'|'duplicate'|'denied'|'ads';
export type CaseData = {triage?:Triage; draftBasis?:string; id?:string; business:string; email:string; profileId:string; mapsUrl:string; address:string; previousAddress:string; type:string; issue:Issue; notice:string; corrections:string; caseNumber:string; status:string; checks:string[]; events:{date:string;title:string;detail:string}[]; draft:string; paid?:boolean; version?:number};
export const emptyCase:CaseData={business:'',email:'',profileId:'',mapsUrl:'',address:'',previousAddress:'',type:'service',issue:'suspended',notice:'',corrections:'',caseNumber:'',status:'Preparing',checks:[],events:[],draft:''};
export const sources=[
 {title:'Suspension and appeals',url:'https://support.google.com/business/answer/4569145',topic:'Appeals'},
 {title:'Business eligibility and representation',url:'https://support.google.com/business/answer/3038177',topic:'Eligibility'},
 {title:'Request ownership',url:'https://support.google.com/business/answer/4566671',topic:'Ownership'},
 {title:'Video verification',url:'https://support.google.com/business/answer/14271705',topic:'Verification'},
 {title:'Missing or delayed reviews',url:'https://support.google.com/business/answer/10313341',topic:'Reviews'},
 {title:'Duplicate profiles',url:'https://support.google.com/business/answer/12756178',topic:'Duplicates'},
 {title:'Move reviews between profiles',url:'https://support.google.com/business/answer/3098204',topic:'Reviews'},
 {title:'New owner limitations',url:'https://support.google.com/business/answer/3403100',topic:'Ownership'},
 {title:'Google Ads suspensions',url:'https://support.google.com/google-ads/answer/9841640',topic:'Google Ads'},
];
export type Step={title:string;description:string;tasks:string[];link?:string;linkLabel?:string;source:number};
export const issues:Record<Issue,{title:string;short:string;description:string;notice:string;steps:Step[]}>={
 suspended:{title:'My Business Profile is suspended',short:'Profile suspension',description:'Your listing says suspended or disabled in Search or Business Profile Manager.',notice:'Prepare your documents before opening Google’s evidence form. Its submission window is 60 minutes.',steps:[
 {title:'Confirm the affected profile',description:'Start with the exact record, not just the business name.',tasks:['Record the profile ID, Maps link and managing email.','Save the notice and the date it appeared.','Check whether an associated account is also restricted. If yes, use the account restriction path first.'],source:0},
 {title:'Review your business information',description:'Compare what the public sees with how your business actually operates.',tasks:['Use the real-world name without added search keywords.','Confirm whether customers visit you or you travel to them.','Review address, category, website and customer-facing hours. Document genuine corrections.'],source:1},
 {title:'Prepare and submit the appeal',description:'Google makes the eligibility decision. Submit a factual, complete record.',tasks:['Gather registration, license or tax evidence and a business utility bill where available. Match name and address.','Open the appeals tool using the correct Google account. Review the stated policy and submit.','If offered an evidence form, attach your prepared files within 60 minutes of opening it.'],link:'https://support.google.com/business/workflow/13569690',linkLabel:'Open Google’s appeals tool',source:0},
 {title:'Record the decision',description:'Keep the same case history together.',tasks:['Save your confirmation and check appeal status. Do not create a replacement profile while under review.','If denied, use the additional-review path with relevant new evidence.','If approved, check public visibility, management access and reviews separately.'],source:0}]},
 restricted:{title:'My Google account is restricted',short:'Account restriction',description:'The appeals tool says an associated Google Account is restricted.',notice:'An unrestricted general account screen does not prove that Business Profile access is unrestricted.',steps:[
 {title:'Capture both account screens',description:'Make a comparison Google support can reproduce.',tasks:['Use the same signed-in email on both screens.','Save the exact restriction notice and the general account status with dates.','List the affected profile IDs without guessing which other business caused this.'],source:0},
 {title:'Use the account restriction route',description:'Address the account restriction before the profile appeal.',tasks:['Check My Account for the restriction appeal.','If the screens conflict or no appeal is available, explain that discrepancy to Business Profile support.','Ask which account/profile relationship is restricted and what correction is required.'],link:'https://myaccount.google.com/restrictions',linkLabel:'Check account restrictions',source:0},
 {title:'Return to the original profile',description:'Keep the original business identity intact.',tasks:['Retain the decision email showing the account outcome.','Once the restriction is lifted, follow the profile appeal route if the listing remains suspended.','Check that the intended owner can manage the original record.'],source:0}]},
 ownership:{title:'I cannot access my business profile',short:'Ownership & access',description:'The listing exists, but you cannot manage it or the wrong account owns it.',notice:'A public listing and management access are two different things. Keep a record of both.',steps:[
 {title:'Identify the exact existing listing',description:'Avoid requesting access to a similarly named duplicate.',tasks:['Record the Maps link, address and review count.','Check authorized accounts you already control.','If an existing owner can help, ask them to invite your business email through People and access.'],source:7},
 {title:'Request access through the right route',description:'Use the existing business entry.',tasks:['For storefront or hybrid businesses, find the existing entry at business.google.com/add and use Request Access when offered.','For a service-area business without a physical shop or office, contact support for “Transfer ownership of listing.”','If no route appears, explain the missing control and include the exact profile identity.'],link:'https://support.google.com/business/answer/4566671',linkLabel:'Follow Google’s ownership steps',source:2},
 {title:'Verify the invitation and owner role',description:'The current owner normally has three days to respond; a later claim option is not guaranteed.',tasks:['Retain the request confirmation and response.','After approval, match the profile ID and verify your role in People and access.','New owners have a seven-day restriction on certain actions, including primary ownership transfer.'],source:7}]},
 verification:{title:'My verification is stuck or rejected',short:'Verification',description:'Google requests verification, or your video was not accepted.',notice:'Use the verification method Google offers for your profile. A pre-recorded promotional video is not verification evidence.',steps:[
 {title:'Read the exact verification request',description:'Save the message before recording again.',tasks:['Record the offered method and any rejection feedback.','Review the location and business type on the profile.','Plan a route that shows real operations without exposing customers or private information.'],source:3},
 {title:'Prepare your recording',description:'Show location, business activity and your authority to operate it.',tasks:['For a storefront, show nearby identifiers and permanent business signage.','For a service business, show location context and relevant tools, equipment or branded materials.','Demonstrate access to employee-only areas, equipment or business documents appropriate to your operation.'],source:3},
 {title:'Record through Google’s flow',description:'Google’s recording flow is the submission route.',tasks:['Record one continuous, unedited video of at least 30 seconds.','Do not include faces, bank details or identity document numbers.','Save the result and follow the offered retry or support instructions if rejected.'],link:'https://support.google.com/business/answer/14271705',linkLabel:'Open the official video guide',source:3}]},
 reviews:{title:'My reviews disappeared',short:'Missing reviews',description:'Your profile returned, but its historical reviews did not.',notice:'Request eligible historical reviews. No service can promise a specific review count or rating.',steps:[
 {title:'Build a before-and-after record',description:'Use dated evidence rather than a remembered total.',tasks:['Save previous Google review notifications or performance emails.','Record current and historical profile IDs and Maps URLs.','Note the reinstatement or relocation date and the observed review count.'],source:4},
 {title:'Identify a delay or a separate record',description:'Missing reviews do not automatically mean deletion.',tasks:['Check whether the reviews appear on another existing profile.','Allow for review checking or post-merge display delays.','Reviews removed for policy violations are not eligible for restoration.'],source:4},
 {title:'Ask support for review recovery',description:'Explain the continuity of the same business.',tasks:['Contact support for reviews missing after reinstatement.','If you moved with the same name, include evidence linking the former and current location.','Ask Google to identify the surviving record before any duplicate cleanup.'],link:'https://support.google.com/business/gethelp',linkLabel:'Contact Business Profile support',source:6}]},
 duplicate:{title:'There are duplicate business profiles',short:'Duplicate profiles',description:'Two or more listings represent the same location or business.',notice:'Do not delete a valuable profile just to make the duplicate disappear. Record the reviews and ownership first.',steps:[
 {title:'Map every record',description:'Similar names are not enough to establish a match.',tasks:['Collect each Maps URL, profile ID when accessible, name, address and review count.','Record which account manages each one.','Distinguish genuine separate locations or eligible departments from same-business duplicates.'],source:5},
 {title:'Prepare the same-business evidence',description:'Explain why these records refer to one continuous business.',tasks:['Document a relocation or accidental duplicate creation.','Compare names, website and phone details; resolve genuine factual discrepancies.','Preserve important owner replies before requesting a merge.'],source:5},
 {title:'Request a reviewed consolidation',description:'Google decides whether a merge is eligible.',tasks:['Provide both records and identify the one you request to retain.','Ask support to confirm the review treatment before proceeding.','Approved merges combine eligible reviews, but owner replies may be lost. Verify the outcome before changing your website links.'],link:'https://support.google.com/business/answer/12756178',linkLabel:'Review Google’s duplicate guidance',source:5}]},
 denied:{title:'My appeal was denied',short:'Denied appeal',description:'You received a decision and need to prepare the next review.',notice:'A stronger next submission explains what is new or corrected. Repeating the same claim does not add evidence.',steps:[
 {title:'Read the actual decision',description:'Separate Google’s words from your theory.',tasks:['Save the full decision, policy link, date and case number.','Check whether the denial mentions an account restriction.','List what the first submission actually contained.'],source:0},
 {title:'Build an evidence comparison',description:'Make the improvement easy for a reviewer to follow.',tasks:['Identify missing documents or inconsistent business facts.','Explain address changes with dates and supporting records.','Write a short summary of genuine corrections and relevant new evidence.'],source:1},
 {title:'Request additional review',description:'Use Google’s denied-request route when available.',tasks:['Open the additional-review link in the official suspension guide.','Reference the original profile and decision.','Keep the confirmation and any subsequent response in your timeline.'],link:'https://support.google.com/business/answer/4569145',linkLabel:'Find the additional-review route',source:0}]},
 ads:{title:'My Google Ads account is suspended',short:'Google Ads',description:'Paid advertising is stopped because of billing or an Ads policy issue.',notice:'Google Ads and Business Profile are separate products. Recovering your Maps listing does not resolve an Ads balance.',steps:[
 {title:'Identify the Ads restriction',description:'Use the customer ID and the exact banner in Google Ads.',tasks:['Record the Ads customer ID and the policy or billing notice.','Distinguish canceled account status from a suspension.','Check whether payment verification or advertiser verification is requested.'],source:8},
 {title:'Follow the stated resolution',description:'The restriction determines the route.',tasks:['For billing, review the outstanding amount and contact Ads billing about available options.','For policy suspension, use Contact Us in the account notice to access the appeal.','Do not create another account to evade the suspension.'],link:'https://support.google.com/google-ads/answer/9841640',linkLabel:'Open Google Ads suspension guidance',source:8},
 {title:'Keep the two recoveries separate',description:'An account cancellation does not erase money owed.',tasks:['Retain payment confirmations or written billing decisions.','Track the Ads decision separately from your Maps profile.','After approval, verify account status before resuming advertising.'],source:8}]}
};
export function evidenceFor(c:CaseData){const base=[{id:'notice',title:'Restriction or decision notice',detail:'Complete screenshot or email, including the date and reason.'},{id:'identity',title:'Exact profile identity',detail:'Business Profile ID and Maps link; Ads customer ID for an Ads case.'}];if(['suspended','restricted','denied','verification'].includes(c.issue))base.push({id:'registration',title:'Business registration or license',detail:'An authentic business record. Review the name and operating-address match.'},{id:'utility',title:'Business utility bill',detail:'A relevant current bill showing the business and location; keep originals.'});if(c.previousAddress)base.push({id:'move',title:'Relocation evidence',detail:'Dated records connecting the former address with the current business.'});if(['reviews','duplicate'].includes(c.issue))base.push({id:'history',title:'Historical review evidence',detail:'Dated Google emails or screenshots; preserve review and reply history.'},{id:'records',title:'Profile comparison',detail:'Identify every affected listing separately, including ownership where known.'});if(c.issue==='ownership')base.push({id:'authority',title:'Proof of authority',detail:'Business records linking you to the company and requested managing email.'});if(c.type==='storefront'||c.type==='hybrid')base.push({id:'signage',title:'Location and signage photos',detail:'Real permanent signage and location context, where relevant.'});return base;}
export function draftFor(c:CaseData){const detail:Record<Issue,string>={suspended:'Please review the eligibility of the original Business Profile and reinstate it if it meets your guidelines.',restricted:'Please identify the restricted account/profile relationship and the official correction or appeal route. If the account status screens disagree, please reconcile that discrepancy.',ownership:'Please help restore legitimate management access to the existing profile through the managing email below. Please specify the official verification route if required.',verification:'Please clarify the outstanding verification requirement and the available verification route for this business.',reviews:'Please investigate and restore eligible historical reviews associated with this same business. Please identify any separate record containing those reviews before taking consolidation action.',duplicate:'Please review the relationship between the existing records and confirm whether consolidation is eligible, which record would remain, and how reviews and owner replies would be handled before any merge or removal.',denied:'Please consider this request for additional review of the denied appeal, including the corrections and new evidence described below.',ads:'Please review the stated Ads account restriction and confirm the required resolution. This request does not authorize a payment or account reactivation.'};return `Subject: ${issues[c.issue].short} — ${c.business||'[Business name]'}${c.caseNumber?' — case '+c.caseNumber:''}\n\nHello ${c.issue==='ads'?'Google Ads':'Google Business Profile'} Support,\n\n${detail[c.issue]}\n\nBusiness: ${c.business||'[Business name]'}\n${c.issue==='ads'?'Ads customer ID':'Business Profile ID'}: ${c.profileId||'[Exact ID]'}\nMaps URL: ${c.mapsUrl||'[Existing Maps URL, if applicable]'}\nManaging email: ${c.email||'[Authorized managing email]'}\nCurrent operating address: ${c.address||'[Operating address supplied privately to support]'}${c.previousAddress?'\nFormer address: '+c.previousAddress:''}\n\nExact notice received:\n${c.notice||'[Paste the actual notice. Do not infer a violation.]'}\n\nCorrections and additional context:\n${c.corrections||'[Describe only changes actually completed and facts you can support.]'}\n\nEvidence available for review:\n${evidenceFor(c).filter(x=>c.checks.includes('evidence-'+x.id)).map(x=>'- '+x.title).join('\n')||'[List only documents you have prepared and will attach.]'}\n\nPlease preserve the existing profile and eligible historical content while reviewing this request. Please explain any specific remaining requirement.\n\nThank you,\n${c.business||'[Business name]'}`;}
export function sampleCase():CaseData{return {...emptyCase,business:'Northline Plumbing',email:'owner@example.com',profileId:'Example profile — not a real ID',address:'Example operating address',type:'service',notice:'Your Business Profile has been suspended.',corrections:'Example: reviewed business name and service-area settings against actual operations.',checks:['step-0-0','step-0-1','step-1-0','evidence-notice','evidence-identity'],events:[{date:new Date().toISOString(),title:'Example case opened',detail:'Fictional business. Explore the workflow without uploading real documents.'}]};}
