import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {activePass} from './commerce';
export function runtime(){return env as unknown as {DB:D1Database;BUCKET:R2Bucket;STRIPE_SECRET_KEY?:string;STRIPE_WEBHOOK_SECRET?:string;STRIPE_PRICE_ID?:string;SITE_URL?:string;PAYMENTS_ENABLED?:string;SUPPORT_EMAIL?:string;OPERATOR_NAME?:string;REFUND_POLICY?:string;LAUNCH_REVIEWED?:string;OWNER_EMAIL?:string;BACKUP_RUNNER_TOKEN_HASH?:string};}
export function db(){const d=runtime().DB;if(!d)throw new Error('Storage unavailable');return d;}
export async function identity(){const u=await getChatGPTUser();if(!u)throw new Error('SIGN_IN_REQUIRED');return u;}
export async function operator(){const u=await identity();if(!runtime().OWNER_EMAIL||u.email.toLowerCase()!==runtime().OWNER_EMAIL!.toLowerCase())throw new Error('FORBIDDEN');return u;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new Error('Request origin is not allowed.');}
export async function owned(id:string,userId:string){const row=await db().prepare('SELECT * FROM cases WHERE id=? AND user_id=?').bind(id,userId).first<{id:string;user_id:string;data:string;version:number;paid:number;paid_until:string|null}>();return row?{...row,paid:activePass(row)?1:0}:null;}
export async function failure(e:unknown){const m=e instanceof Error?e.message:'';if(m==='SIGN_IN_REQUIRED')return Response.json({error:'Sign in to save your case.'},{status:401});if(m==='FORBIDDEN')return Response.json({error:'This page is restricted to the site operator.'},{status:403});if(m==='RATE_LIMIT')return Response.json({error:'Too many requests. Wait a minute, then try again.'},{status:429,headers:{'Retry-After':'60'}});const known=/^(Support |Operator |Backup |Restore |Document |Case |This case |Save your |Choose |Maximum |Only |Each case |You have |Checkout |Request origin |This page |No |Enter |Confirm |The notice |The backup )/.test(m);const reference=crypto.randomUUID().slice(0,12);const validation=e instanceof Error&&(e.name==='ZodError'||e.name==='SyntaxError');if(!known&&!validation){console.error(JSON.stringify({event:'request_failed',reference,category:e instanceof Error?e.name:'Unknown'}));await (await import('./diagnostics')).recordDiagnostic('server_request','server');}return Response.json({error:known?m:validation?'Check the form fields and try again.':'The service is temporarily unavailable. Try again shortly.',...(!known&&!validation?{reference}:{})},{status:known||validation?400:503});}
export async function launchChecks(){const e=runtime();const s=await (await import('./settings')).settings();return [{label:'Stripe API key',ready:!!e.STRIPE_SECRET_KEY},{label:'Stripe webhook secret',ready:!!e.STRIPE_WEBHOOK_SECRET},{label:'One-time price',ready:!!e.STRIPE_PRICE_ID},{label:'Canonical HTTPS site address',ready:!!e.SITE_URL&&/^https:\/\//.test(e.SITE_URL)},{label:'Operator identity',ready:!!s.operatorName},{label:'Customer support email',ready:!!s.supportEmail},{label:'Purchase and refund terms',ready:!!s.refundPolicy},{label:'Launch review completed',ready:s.termsReviewed&&s.browserReviewed},{label:'Payment collection enabled',ready:e.PAYMENTS_ENABLED==='true'}];}
export async function paymentReady(){return (await launchChecks()).every(c=>c.ready);}
export async function rateLimit(userId:string,action:string,max=30){const now=Date.now();const key=`${action}:${userId}:${Math.floor(now/60000)}`;const r=await db().prepare('INSERT INTO request_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+120000).first<{count:number}>();await db().prepare('DELETE FROM request_limits WHERE expires<?').bind(now).run();if((r?.count||0)>max)throw new Error('RATE_LIMIT');}
