// Decrypt and verify into a NEW private folder. Never mutates production.
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {decryptBackup,bytesHash} from '../lib/backup-crypto.ts';
const [input,output]=process.argv.slice(2);if(!input||!output||!process.env.PROFILEPATH_BACKUP_PASSPHRASE)throw Error('Usage: PROFILEPATH_BACKUP_PASSPHRASE=... node --experimental-strip-types scripts/restore-backup.mjs backup.ppbackup NEW_DIRECTORY');
const backup=await decryptBackup(new Uint8Array(await readFile(input)),process.env.PROFILEPATH_BACKUP_PASSPHRASE);if(backup.format!=='profilepath-system-backup'||backup.version!==1)throw Error('Unsupported system backup.');
const allowed=['cases','case_versions','customers','evidence','payments','support_tickets','support_messages','site_settings'];
if(Object.keys(backup.tables).some(t=>!allowed.includes(t)))throw Error('Unknown backup table.');
const fingerprint=await bytesHash(new TextEncoder().encode(JSON.stringify(backup.tables)));if(fingerprint!==backup.fingerprint)throw Error('Manifest checksum mismatch.');
if(!Array.isArray(backup.objects)||!Array.isArray(backup.tables.evidence))throw Error('Invalid object manifest.');const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(id);if(backup.objects.some(o=>!validId(o.id))||backup.tables.evidence.some(o=>!validId(o.id)))throw Error('Invalid document identifier.');const evidenceIds=new Set(backup.tables.evidence.map(o=>o.id));if(evidenceIds.size!==backup.tables.evidence.length||backup.objects.some(o=>!evidenceIds.has(o.id)))throw Error('Document identifier set mismatch.');const files=new Map(backup.objects.map(o=>[o.id,o]));if(files.size!==backup.objects.length||files.size!==backup.tables.evidence.length)throw Error('Document manifest mismatch.');
for(const file of backup.tables.evidence){const object=files.get(file.id);if(!/^[a-zA-Z0-9_-]{1,100}$/.test(file.id)||!object)throw Error('Invalid document identifier.');const bytes=Buffer.from(object.base64,'base64');if(bytes.length!==file.size||await bytesHash(bytes)!==object.sha256)throw Error('Document integrity check failed.');}
await mkdir(output,{mode:0o700});await mkdir(output+'/objects',{mode:0o700});
const quote=v=>v===null?'NULL':typeof v==='number'?String(v):"'"+String(v).replaceAll("'","''")+"'";
let sql='-- Restore into a NEW empty D1 database after applying this repository’s migrations.\n-- Keep PAYMENTS_ENABLED=false. Reconcile payment records before restoring entitlements.\n';
for(const table of allowed){for(const original of backup.tables[table]||[]){const row={...original};if(table==='cases'){row.paid=0;row.paid_until=null;}if(table==='site_settings'&&row.key!=='launch')throw Error('Unexpected secret setting.');const columns=Object.keys(row);if(columns.some(c=>!/^[a-z_]+$/.test(c)))throw Error('Invalid column.');const large=columns.filter(c=>typeof row[c]==='string'&&Buffer.byteLength(row[c])>8000);const initial=Object.fromEntries(columns.map(c=>[c,large.includes(c)?'':row[c]]));const insert=`INSERT INTO ${table} (${columns.join(',')}) VALUES (${columns.map(c=>quote(initial[c])).join(',')});\n`;if(Buffer.byteLength(insert)>90000)throw Error('Restore row exceeds SQL safety limit.');sql+=insert;for(const column of large){const points=Array.from(row[column]);const pk=table==='site_settings'?'key':'id';for(let n=0;n<points.length;n+=8000)sql+=`UPDATE ${table} SET ${column}=${column}||${quote(points.slice(n,n+8000).join(''))} WHERE ${pk}=${quote(row[pk])};\n`;}}}
await writeFile(output+'/restore.sql',sql,{mode:0o600,flag:'wx'});for(const object of backup.objects)await writeFile(output+'/objects/'+object.id,Buffer.from(object.base64,'base64'),{mode:0o600,flag:'wx'});await writeFile(output+'/manifest.json',JSON.stringify({...backup,objects:backup.objects.map(({base64,...o})=>o)},null,2),{mode:0o600,flag:'wx'});console.log('Verified restore files prepared. Apply repository migrations to fresh D1, import restore.sql, upload objects by ID to fresh R2, and verify ownership/downloads before cutover.');
